image:
- Visual Studio 2017
- Visual Studio 2015
- Visual Studio 2013

test_script:
- cmd: IF DEFINED CI_WINDOWS (ECHO CI_WINDOWS IS defined)
- cmd: IF "%CI_WINDOWS%"=="true" ECHO This is Windows!
- ps: IF (!$env:CI_WINDOWS) {throw 'CI_WINDOWS environment variable is not defined'}
- ps: IF ($env:CI_WINDOWS -ne "true") {throw 'CI_WINDOWS environment variable is not set to "true"'}

build: off
